# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
    command = "rm * -r;git clone https://github.com/glazec/hexo-cheatsheets-demo.git;cd hexo-cheatsheets-demo;npm install;npx hexo generate"
    publish = "hexo-cheatsheets/public"